name: Android build

on:
  push:
    branches: [ "master" ]

jobs:
  build:

    runs-on: obuntu-latest
    steps:
          - name: Run Tests
            run: ./gradlew test

          - name: Build Project
            run: ./gradlew assemble
